spring:
  application:
    name: secure-gateway
    
logging:
  level:
    com.verisure.vcp.securegateway.interceptor.RequestResponseLoggingInterceptor: DEBUG
    org.springframework.web.*: DEBUG
    org.springframework.seurity.*: DEBUG
    
    
server:
  port: 8443
  ssl:
    key-store: classpath:server-keystore.jks
    key-store-password: secret
    key-alias: es1pocmom01v
    trust-store: classpath:server-truststore.jks
    trust-store-password: secret
    enabled: true
    client-auth: need
http:
  client:
    backend: 
      protocol: https
      host: es1pocmom01v
      #host: es1pocmom01v.sp.securitasdirect
      #host: localhost
      port: 8243
      ssl-host-name-verification: false
security:
  oauth2:
    client:
      access-token-uri: https://es1pocmom01v:8243/token
      userAuthorizationUri: https://es1pocmom01v:8243/authorization
      client-id: y8I_kYBFiA8snewZxy4WKfzduREa
      client-secret: 2nNJnAc1kPbczQt7TQuU2TZUZ7Aa
      
      #access-token-uri: https://localhost:8243/token
      #client-id: ICLIQ5F4p_3Vv9DtttQz6Yano_8a
      #client-secret: St_O2ci3Z3sRUcSRek3Y0BqunoMa      